---
stages:
  - vulnerability
  - build
  - dist

variables:
  version: 0.1.0

snyk-scan:
  stage: vulnerability
  image: node:14.2
  before_script:
    - apt install -y wget tar
    - wget -q https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz -O /tmp/go1.14.4.linux-amd64.tar.gz
    - tar -C /usr/local -xzf /tmp/go1.14.4.linux-amd64.tar.gz
  script:
    - export PATH=$PATH:/usr/local/go/bin
    - npm install -g snyk
    - snyk auth $SNYK_TOKEN
    - snyk test

compile-windows:
  stage: build
  image: golang:1.14
  script:
    - go mod download
    - if [ -n "$CI_COMMIT_TAG" ]; then export version=$CI_COMMIT_TAG; fi
    - GOOS=windows go build -ldflags "-X main.commit=$CI_COMMIT_SHORT_SHA -X main.version=$version"
  artifacts:
    paths:
      - lifx-streamdeck.exe
  except:
    - schedules

compile-mac:
  stage: build
  image: golang:1.14
  script:
    - go mod download
    - if [ -n "$CI_COMMIT_TAG" ]; then export version=$CI_COMMIT_TAG; fi
    - echo "implement"
    - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.commit=$CI_COMMIT_SHORT_SHA -X main.version=$version"
  artifacts:
    paths:
      - lifx-streamdeck
  except:
    - schedules

generate-bundle:
  stage: dist
  image: ubuntu:20.04
  before_script:
    - apt update && apt install -y zip
  script:
    - mkdir dev.sean.lifx.sdPlugin
    - cp lifx-streamdeck.exe dev.sean.lifx.sdPlugin
    - cp lifx-streamdeck dev.sean.lifx.sdPlugin
    - cp manifest.json dev.sean.lifx.sdPlugin
    - cp property-inspector/* dev.sean.lifx.sdPlugin
    - zip -r dev.sean.lifx.streamDeckPlugin dev.sean.lifx.sdPlugin
  artifacts:
    paths:
      - dev.sean.lifx.streamDeckPlugin
  except:
    - schedules