// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	golifx "gitlab.com/wwsean08/golifx"

	mock "github.com/stretchr/testify/mock"

	models "gitlab.com/wwsean08/lifx-streamdeck/models"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// Debug provides a mock function with given fields:
func (_m *Controller) Debug() (*models.Debug, error) {
	ret := _m.Called()

	var r0 *models.Debug
	if rf, ok := ret.Get(0).(func() *models.Debug); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Debug)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DiscoverDevices provides a mock function with given fields:
func (_m *Controller) DiscoverDevices() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCurrentColor provides a mock function with given fields: _a0
func (_m *Controller) GetCurrentColor(_a0 *golifx.Device) (*golifx.HSBK, error) {
	ret := _m.Called(_a0)

	var r0 *golifx.HSBK
	if rf, ok := ret.Get(0).(func(*golifx.Device) *golifx.HSBK); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golifx.HSBK)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*golifx.Device) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrentState provides a mock function with given fields: _a0
func (_m *Controller) GetCurrentState(_a0 *golifx.Device) (*golifx.DeviceState, error) {
	ret := _m.Called(_a0)

	var r0 *golifx.DeviceState
	if rf, ok := ret.Get(0).(func(*golifx.Device) *golifx.DeviceState); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golifx.DeviceState)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*golifx.Device) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDevices provides a mock function with given fields:
func (_m *Controller) GetDevices() map[string]*golifx.Device {
	ret := _m.Called()

	var r0 map[string]*golifx.Device
	if rf, ok := ret.Get(0).(func() map[string]*golifx.Device); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*golifx.Device)
		}
	}

	return r0
}

// GetPowerState provides a mock function with given fields: _a0
func (_m *Controller) GetPowerState(_a0 *golifx.Device) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*golifx.Device) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*golifx.Device) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetBrightness provides a mock function with given fields: _a0
func (_m *Controller) SetBrightness(_a0 *models.BrightnessSettings) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BrightnessSettings) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetColor provides a mock function with given fields: _a0
func (_m *Controller) SetColor(_a0 *models.ColorSettings) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ColorSettings) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPowerState provides a mock function with given fields: _a0, _a1
func (_m *Controller) SetPowerState(_a0 *models.PowerSettings, _a1 bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.PowerSettings, bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetScene provides a mock function with given fields: _a0
func (_m *Controller) SetScene(_a0 *models.SceneSettings) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.SceneSettings) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWaveform provides a mock function with given fields: _a0
func (_m *Controller) SetWaveform(_a0 *models.WaveFormSettings) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.WaveFormSettings) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TogglePowerState provides a mock function with given fields: _a0
func (_m *Controller) TogglePowerState(_a0 *models.ToggleSettings) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ToggleSettings) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGlobalSettings provides a mock function with given fields: _a0
func (_m *Controller) UpdateGlobalSettings(_a0 *models.GlobalSettings) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.GlobalSettings) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
